### ISSUE TITLE
Integrate with Vercel Analytics

### ISSUE THREAD

**Issue by Atinux** [nuxt-community/web-vitals-module#13]
I believe it would be nice to support Vercel analytics since they also use `web-vitals` for their API.

Vercel did a prototype based on this module actually: https://github.com/vercel/nuxt-plugin-vercel

We could imagine a `provider` option, default to `ga` and overwritten with `NUXT_VITALS_PROVIDER` or directly having `NUXT_VITALS_URL`?

**Comment by daliborgogic** [comment]
Can't test Vercel integration. 
`Analytics is currently only available for projects using Next.js and Gatsby.` 
We need `provider` option because `url` and `payload` data are different between `ga` and `vercel`. 
First we need to solve how to get access/enable analytics for `nuxt` project.

**Comment by daliborgogic** [comment]
This is how i see `providers` https://gist.github.com/daliborgogic/a67cc5362ed9330858c3114540ad8960

**Comment by daliborgogic** [comment]
Branch [providers](https://github.com/nuxt-community/vitals-module/tree/providers)

**Comment by daliborgogic** [comment]
If we use target `static` and `buildModules` we dont have during the build `process.env.VERCEL_ANALYTICS_ID`.   
Status `400`.
Demo: https://nxt-vercel.vercel.app/ 
Other works as exepcted. Dinamicaly applied provider based on option `trackingID`.
Problem is only in `VERCEL_ANALYTICS_ID` environment variable.

**Comment by daliborgogic** [comment]
![Screenshot 2020-11-07 at 18 26 07](https://user-images.githubusercontent.com/5895389/98447643-bee3b500-2126-11eb-90cc-7892d8fca190.png)

**Comment by pi0** [comment]
Hi :D

> Other works as expected. Dinamicaly applied provider based on option trackingID.

I think you can leverage [runtimeConfig](https://nuxtjs.org/docs/2.x/directory-structure/nuxt-config#runtimeconfig) for this.

**Comment by daliborgogic** [comment]
@pi0 I try but during the build on `vercel` we dont have `VERCEL_ANALYTICS_ID` environment for some reason...

**Comment by daliborgogic** [comment]
I notice for `gatsby` they have `GATSBY_VERCEL_ANALYTICS_ID`, then i/we can expect for nuxt to be `NUXT_VERCEL_ANALYTICS_ID`. For now `vercel` official have support ONLY for `gatsby` and for `next`...

**Comment by pi0** [comment]
Hmm interesting :thinking:  

For Gatsby they alias it here: https://github.com/vercel/vercel/blob/5bea99c1d9817cbfa3983f2386bd3083f5129d73/packages/now-static-build/src/utils/gatsby.ts#L23

For `VERCEL_ANALYTICS_ID`, let me ask :)

**Comment by pi0** [comment]
Module released with vercel support. Waiting for vercel team to make final touches on their side :)
