### ISSUE TITLE
Add option to disable logging when sending

### ISSUE THREAD

**Issue by ymmooot** [nuxt-community/web-vitals-module#18]
This module logs every time the `send` method is called. 
I want to disable it in production build.

https://github.com/nuxt-community/web-vitals-module/blob/63fa35e9ddee5bda1b2c401b3bd520cecaed71eb/src/runtime/utils.ts#L29

**Comment by pi0** [comment]
Thanks for reporting @ymmooot. Actually `options.debug` is ignored here which is causing issue.
